services:
  - type: web
    name: whaatachi
    env: node
    region: ohio
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_PASSCODE
        sync: false
      - key: CORS_ORIGIN
        sync: false
